version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=python/api.py
      - FLASK_ENV=production
    restart: unless-stopped 